// Vercel Serverless Function — receives consultation-form submissions
// from contact.html and index.html, stores each lead in Vercel Blob, and
// forwards the lead to info@fasmedicalsummitrcm.com when Resend is configured.
//
// Required env var (set in Vercel project settings):
//   BLOB_READ_WRITE_TOKEN — generated by connecting a private Vercel Blob store.
//
// Optional env vars:
//   RESEND_API_KEY  — get one free at https://resend.com (3,000 emails/mo).
//   LEAD_TO_EMAIL    — destination (default: info@fasmedicalsummitrcm.com)
//   LEAD_FROM_EMAIL  — sender (default: 'FAS Lead Form <onboarding@resend.dev>')
//
// Until Blob or Resend is set up, leads are still captured in the Vercel
// function log so the form keeps working while deployment wiring is finished.

import { randomUUID } from 'node:crypto';
import { put } from '@vercel/blob';

const TO_EMAIL = process.env.LEAD_TO_EMAIL || 'info@fasmedicalsummitrcm.com';
const FROM_EMAIL = process.env.LEAD_FROM_EMAIL || 'FAS Lead Form <onboarding@resend.dev>';

function escapeHtml(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function cleanField(value, max = 4000) {
  return String(value ?? '').trim().slice(0, max);
}

function getClientIp(req) {
  const forwarded = req.headers['x-forwarded-for'];
  if (typeof forwarded === 'string' && forwarded.trim()) {
    return forwarded.split(',')[0].trim();
  }
  return req.socket?.remoteAddress || '';
}

function buildLeadRecord(data, req) {
  const createdAt = new Date().toISOString();
  const id = `${createdAt.replace(/[-:.TZ]/g, '').slice(0, 14)}-${randomUUID()}`;

  return {
    id,
    createdAt,
    status: 'new',
    name: cleanField(data.name, 200),
    email: cleanField(data.email, 320).toLowerCase(),
    phone: cleanField(data.phone, 80),
    practice: cleanField(data.practice, 240),
    collection: cleanField(data.collection, 120),
    providers: cleanField(data.providers, 40),
    specialty: cleanField(data.specialty, 160),
    ehr: cleanField(data.ehr, 160),
    message: cleanField(data.message, 4000),
    source: cleanField(data._source, 500),
    referrer: cleanField(data._referrer, 1000),
    userAgent: cleanField(req.headers['user-agent'], 500),
    ip: cleanField(getClientIp(req), 80),
  };
}

async function storeLead(record) {
  if (!process.env.BLOB_READ_WRITE_TOKEN) {
    return { stored: false, mode: 'blob_not_configured' };
  }

  const day = record.createdAt.slice(0, 10);
  const pathname = `leads/${day}/${record.id}.json`;
  const blob = await put(
    pathname,
    JSON.stringify(record, null, 2),
    {
      access: 'private',
      addRandomSuffix: false,
      allowOverwrite: false,
      contentType: 'application/json',
    },
  );

  return { stored: true, mode: 'blob', pathname: blob.pathname };
}

function buildEmailBody(record, storage) {
  const fields = [
    ['Lead ID',           record.id],
    ['Storage',           storage.stored ? storage.pathname : storage.mode],
    ['Name',              record.name],
    ['Email',             record.email],
    ['Phone',             record.phone],
    ['Practice',          record.practice],
    ['Monthly Collection',record.collection],
    ['No. of Providers',  record.providers],
    ['Specialty',         record.specialty],
    ['EHR / PMS',         record.ehr],
    ['Message',           record.message],
    ['Submitted From',    record.source],
    ['Referrer',          record.referrer],
    ['Timestamp',         record.createdAt],
  ];

  const rows = fields
    .filter(([, v]) => v !== undefined && v !== null && String(v).trim() !== '')
    .map(([k, v]) => `<tr>
        <td style="padding:8px 14px;background:#f8f6f1;border-bottom:1px solid #ece6d8;font-family:monospace;font-size:12px;color:#7a6d4f;width:180px;vertical-align:top;">${escapeHtml(k)}</td>
        <td style="padding:8px 14px;border-bottom:1px solid #ece6d8;font-size:14px;color:#1a1a1a;vertical-align:top;">${escapeHtml(v).replace(/\n/g,'<br>')}</td>
      </tr>`)
    .join('');

  const html = `<!doctype html>
<html><body style="margin:0;padding:32px;background:#fafaf6;font-family:-apple-system,BlinkMacSystemFont,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #ece6d8;">
    <div style="padding:24px 28px;background:#0A1220;color:#F4EFE6;">
      <div style="font-family:Georgia,serif;font-size:20px;font-weight:500;margin-bottom:4px;">New Consultation Request</div>
      <div style="font-size:13px;color:#C9A961;font-family:monospace;letter-spacing:0.04em;">FAS MEDICAL SUMMIT RCM</div>
    </div>
    <table style="width:100%;border-collapse:collapse;">${rows}</table>
    <div style="padding:18px 28px;background:#f8f6f1;font-size:12px;color:#7a6d4f;border-top:1px solid #ece6d8;">
      Reply directly to this email to respond to ${escapeHtml(record.name || 'the lead')}.
    </div>
  </div>
</body></html>`;

  const text = fields
    .filter(([, v]) => v !== undefined && v !== null && String(v).trim() !== '')
    .map(([k, v]) => `${k}: ${v}`)
    .join('\n');

  return { html, text };
}

export default async function handler(req, res) {
  // CORS / method
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(204).end();
  }
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'method_not_allowed' });
  }

  // Body — Vercel parses JSON automatically when content-type is application/json.
  const data = (req.body && typeof req.body === 'object') ? req.body : {};

  // Honeypot — silently accept and discard known bot submissions
  if (data.website_url) {
    return res.status(200).json({ ok: true });
  }

  // Validate
  for (const f of ['name', 'email', 'phone']) {
    if (!data[f] || !String(data[f]).trim()) {
      return res.status(400).json({ error: `${f}_required` });
    }
  }
  if (!/.+@.+\..+/.test(String(data.email))) {
    return res.status(400).json({ error: 'invalid_email' });
  }

  const record = buildLeadRecord(data, req);
  let storage;
  try {
    storage = await storeLead(record);
  } catch (e) {
    console.error('[LEAD_STORAGE_ERROR]', e?.message || e);
    storage = { stored: false, mode: 'blob_error' };
  }

  // Log every accepted lead so storage/email issues are visible during review.
  console.log('[LEAD]', JSON.stringify({ ...record, storage }));

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return res.status(200).json({
      ok: true,
      leadId: record.id,
      mode: storage.stored ? 'stored_only' : 'logged_only',
      storage: storage.mode,
    });
  }

  const { html, text } = buildEmailBody(record, storage);
  const subject = `New lead: ${record.name}${record.practice ? ` — ${record.practice}` : ''}`;

  try {
    const r = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: [TO_EMAIL],
        reply_to: record.email,
        subject,
        html,
        text,
      }),
    });

    if (!r.ok) {
      const errBody = await r.text();
      console.error('[RESEND_FAIL]', r.status, errBody);
      // Lead is stored/logged. Tell client it succeeded so they don't retry.
      return res.status(200).json({
        ok: true,
        leadId: record.id,
        mode: storage.stored ? 'stored_only' : 'logged_only',
        warning: 'email_send_failed',
      });
    }

    return res.status(200).json({
      ok: true,
      leadId: record.id,
      mode: storage.stored ? 'stored_and_emailed' : 'emailed_only',
    });
  } catch (e) {
    console.error('[LEAD_EMAIL_ERROR]', e?.message || e);
    return res.status(200).json({
      ok: true,
      leadId: record.id,
      mode: storage.stored ? 'stored_only' : 'logged_only',
      warning: 'email_error',
    });
  }
}
